apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: egressmgr
  name: egressmgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egressmgr
  template:
    metadata:
      labels:
        app: egressmgr
    spec:
      containers:
      - image: kallanseto/egressmgr:master
        name: egressmgr
      serviceAccountName: egressmgr
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: egressmgr
  name: egressmgr
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: egressmgr
